# Generated by Django 3.0.2 on 2020-02-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterid',
            name='voter_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
