# Generated by Django 3.0.2 on 2020-02-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_voterid_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('constituency', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=20)),
            ],
        ),
    ]
