# Generated by Django 3.0.2 on 2020-02-05 06:17

from django.db import migrations, models
import django.db.models.deletion
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('election', '0003_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.FileField(upload_to=election.models.user_directory_path)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CandidateProfile')),
            ],
        ),
    ]
