# Generated by Django 3.0.2 on 2020-02-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proofread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('comments', models.TextField(default='')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.CandidateRegistrations')),
            ],
        ),
    ]
